[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "frontend/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true